var chArr=[
	{id:1,txt:'手机',cardId:0},
	{id:2,txt:'笔记本',cardId:0},
	{id:3,txt:'平板',cardId:0},
	{id:4,txt:'智能穿戴&VR',cardId:0},
	{id:5,txt:'智能家居',cardId:0},
	{id:6,txt:'智慧屏',cardId:0},
	{id:7,txt:'耳机音箱',cardId:0},
	{id:8,txt:'配件',cardId:0},
	{id:9,txt:'生态产品',cardId:0},
	{id:10,txt:'增值服务&其他',cardId:0},
	/* ID1 */
	{id:11,img:'img/index/floor2-ph2.png',txt:'HUAWEI Mate系列',cardId:1},
	{id:12,img:'img/index/floor2-ph3.png',txt:'HUAWEI P系列',cardId:1},
	{id:13,img:'img/index/floor2-ph4.png',txt:'HUAWEI nova系列',cardId:1},
	{id:14,img:'img/index/floor2-ph5.png',txt:'HUAWEI 畅享系列',cardId:1},
	{id:15,img:'img/index/floor2-ph6.png',txt:'HUAWEI 麦芒系列',cardId:1},
	{id:16,img:'img/index/floor2-ph7.png',txt:'荣耀 V系列',cardId:1},
	{id:17,img:'img/index/floor2-ph8.png',txt:'荣耀 HONOR系列',cardId:1},
	{id:18,img:'img/index/floor2-ph9.png',txt:'荣耀 X系列',cardId:1},
	{id:19,img:'img/index/floor5-ph10.jpg',txt:'荣耀 Play系列',cardId:1},
	/* ID2 */
	{id:21,img:'img/index/floor3-ph24.png',txt:'HUAWEI Mate系列',cardId:2},
	{id:22,img:'img/index/floor3-ph25.png',txt:'HUAWEI P系列',cardId:2},
	{id:23,img:'img/index/floor3-ph26.png',txt:'HUAWEI nova系列',cardId:2},
	{id:24,img:'img/index/floor3-ph27.png',txt:'HUAWEI 畅享系列',cardId:2},
	{id:25,img:'img/index/floor3-ph28.png',txt:'HUAWEI 麦芒系列',cardId:2},
	{id:26,img:'img/index/floor3-ph29.png',txt:'荣耀 V系列',cardId:2},
	{id:27,img:'img/index/floor3-ph31.png',txt:'荣耀 HONOR系列',cardId:2},
	{id:28,img:'img/index/floor6-ph2.jpg',txt:'荣耀 X系列',cardId:2},
	{id:29,img:'img/index/floor6-ph3.jpg',txt:'荣耀 Play系列',cardId:2},
	/* ID3 */
	{id:31,img:'img/index/floor3-ph24.png',txt:'HUAWEI Mate系列',cardId:3},
	{id:32,img:'img/index/floor3-ph25.png',txt:'HUAWEI P系列',cardId:3},
	{id:33,img:'img/index/floor3-ph26.png',txt:'HUAWEI nova系列',cardId:3},
	{id:34,img:'img/index/floor3-ph27.png',txt:'HUAWEI 畅享系列',cardId:3},
	{id:35,img:'img/index/floor3-ph28.png',txt:'HUAWEI 麦芒系列',cardId:3},
	{id:36,img:'img/index/floor3-ph29.png',txt:'荣耀 V系列',cardId:3},
	{id:37,img:'img/index/floor3-ph31.png',txt:'荣耀 HONOR系列',cardId:3},
	{id:38,img:'img/index/floor6-ph2.jpg',txt:'荣耀 X系列',cardId:3},
	{id:39,img:'img/index/floor6-ph3.jpg',txt:'荣耀 Play系列',cardId:3}
]